### ISSUE TITLE
关于刷新数据的问题 树会总会剩下几个NodeView遗留下来

### ISSUE THREAD

**Issue by njwl434** [owant/ThinkMap#13]
关于刷新数据的问题 数据多的时候树会总会剩下几个NodeView遗留下来 
用的这个方法更新的数据setTreeModel(treeModel);
多setTreeModel 几次 才没有了

**Comment by owant** [comment]
有考虑到，感觉数据太多也不行要约束一下

**Comment by njwl434** [comment]
问题解决了  重新更新数据前调用这个方法就解决了removeAllViews();
