### ISSUE TITLE
数据一多后面全是重复的，没法用

### ISSUE THREAD

**Issue by njwl434** [owant/ThinkMap#14]
数据一多后面全是重复的，没法用 ，树同级分叉多的情况下。都重叠了。这怎么弄呢？

**Comment by owant** [comment]
提供一下截图或者和Android版等信息

**Comment by njwl434** [comment]
![Screenshot_2019-08-07-10-12-48-593_com owant thin](https://user-images.githubusercontent.com/24601708/62589522-1976db80-b8fc-11e9-9c05-ff129594c1e7.png)
![Screenshot_2019-08-07-10-12-39-210_com owant thin](https://user-images.githubusercontent.com/24601708/62589525-1d0a6280-b8fc-11e9-84fd-a424af0bf0ba.png)
android 9.0  从后面开始就一直重复

**Comment by owant** [comment]
![image](https://user-images.githubusercontent.com/10327673/62695812-a2c80400-ba09-11e9-91a3-fd3bd1abf4e2.png)
对于这种情况要进行优化。
1、可以考虑子控件根据层结构不断缩小适配；
2、对于移动位置计算的算法进行纠正；

**Comment by njwl434** [comment]
最好还是你优化下吧,毕竟和我有一样忧虑的还有很多人,做kpi绩效,工厂流程这样的软件这个工具,基本是很常见的需求。还有最好做一个放json的地方,大家基本用的多数都是展示后台json的 @owant
