### ISSUE TITLE
能不能帮忙实现一下双指缩放功能啊

### ISSUE THREAD

**Issue by chengfan2017** [owant/ThinkMap#19]

**Comment by owant** [comment]
以前的代码有。现在的缩放是点击进行缩放，双指缩放效果不太好去掉了。如果你需要可以看看历史记录。

**Comment by chengfan2017** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
