### ISSUE TITLE
example code该怎么用？

### ISSUE THREAD

**Issue by Thorlph** [owant/ThinkMap#2]
请问一下最后两行的代码
binding.testTreeView.setTreeLayoutManager(new RightTreeLayoutManager(dx, dy, mHeight));
binding.testTreeView.setTreeModel(tree);
binding是什么对象来的？
是指需要绑定的view吗？

**Comment by owant** [comment]
DataBinding 。use  findViewById(R.id.tree_view) resplace the "binding"
