### ISSUE TITLE
Android7.1.2    演示—App版本情况   部分区域无法控制问题

### ISSUE THREAD

**Issue by Mr414Zheng** [owant/ThinkMap#6]
调试的手机是 魅族note6 ，“ 演示—App版本情况”  中node“V1.0.3”以下部分全部不可控。 
用README 里的使用方法创建的思维导图也出现了显示不全问题（但是在另一部5.1手机上一切正常）

`final NodeModel<String> nodeA = new NodeModel<>("剑灵");
        final NodeModel<String> nodeB = new NodeModel<>("穿越火线");
        final NodeModel<String> nodeC = new NodeModel<>("QQ飞车");
        final NodeModel<String> nodeD = new NodeModel<>("QQ炫舞");
        final NodeModel<String> nodeE = new NodeModel<>("QQ三国");
        final NodeModel<String> nodeF = new NodeModel<>("地下城与勇士");
        final NodeModel<String> nodeG = new NodeModel<>("英雄联盟");
        final NodeModel<String> nodeH = new NodeModel<>("剑灵PC版");
        final NodeModel<String> nodeI = new NodeModel<>("剑灵手游版");
        final NodeModel<String> nodeJ = new NodeModel<>("冒险岛");
        final NodeModel<String> nodeK = new NodeModel<>("龙之谷");
        final NodeModel<String> nodeL = new NodeModel<>("传奇世界");
        final NodeModel<String> nodeM = new NodeModel<>("热血传奇");
        final NodeModel<String> nodeN = new NodeModel<>("永恒之塔");
        final NodeModel<String> nodeO = new NodeModel<>("彩虹岛");
        final NodeModel<String> nodeP = new NodeModel<>("我的世界");
        final NodeModel<String> nodeQ = new NodeModel<>("守望先锋");
        final NodeModel<String> nodeR = new NodeModel<>("炉石传说");
        final NodeModel<String> nodeS = new NodeModel<>("天谕");
        final NodeModel<String> nodeT = new NodeModel<>("风暴英雄");
        final NodeModel<String> nodeU = new NodeModel<>("无尽战区");
        final NodeModel<String> nodeV = new NodeModel<>("龙魂时刻");
        final NodeModel<String> nodeW = new NodeModel<>("梦幻西游PC版");
        final NodeModel<String> nodeX = new NodeModel<>("梦幻西游手游版");
        final NodeModel<String> nodeY = new NodeModel<>("魔兽世界");
        final NodeModel<String> nodeZ = new NodeModel<>("梦幻西游");
        final NodeModel<String> node1 = new NodeModel<>("游戏运营商");
        final NodeModel<String> node2 = new NodeModel<>("腾讯");
        final NodeModel<String> node3 = new NodeModel<>("盛大");
        final NodeModel<String> node4 = new NodeModel<>("网易");

        final TreeModel<String> tree = new TreeModel<>(node1);
        tree.addNode(node1, node2, node3, node4);
        tree.addNode(node2, nodeA, nodeB, nodeC, nodeD, nodeE, nodeF, nodeG);
        tree.addNode(node3, nodeJ, nodeK, nodeL, nodeM, nodeN, nodeO);
        tree.addNode(node4, nodeP, nodeQ, nodeR, nodeS, nodeT, nodeU, nodeV, nodeY, nodeZ);
        tree.addNode(nodeA, nodeH, nodeI);
        tree.addNode(nodeZ, nodeW, nodeX);

        int dx = DensityUtils.dp2px(this, 60);
        int dy = DensityUtils.dp2px(this, 30);
        int mHeight = DensityUtils.dp2px(this, 720);
        //int mHeight = DensityUtils.dp2px(this, 1080);

        TreeView testTreeView = new TreeView(this);
        testTreeView.setTreeLayoutManager(new RightTreeLayoutManager(dx, dy, mHeight));
        testTreeView.setTreeModel(tree);

        setContentView(testTreeView);`

**Comment by owant** [comment]
你好，尽可能的输入屏幕的高度。点不了是由于TreeView的大小没有包括子控件的区域。我那时候想到的是每一次添加子控件就进行一次宽高的计算。这个计算有时候出现问题。需要优化一下，我有时间后再修复好。

**Comment by Mr414Zheng** [comment]
非常感谢。
