### ISSUE TITLE
导图的拖拽时间仅限当前显示的区域，超过的区域无法拖拽

### ISSUE THREAD

**Issue by liwentao19881010** [owant/ThinkMap#8]
![image](https://user-images.githubusercontent.com/22782974/34094348-cdf77f9a-e407-11e7-8dea-5accb9ed1bbe.png)
如图所示，拖拽时间超过红框部分就无法拖拽了

**Comment by t50303866** [comment]
同时超出窗口部分，也无点击事件

**Comment by t50303866** [comment]
通过一晚上的测试，发现是因为滑动监听作用在父view上，而TreeView的外层是FrameLayout或者是LinearLayout最大是match_parent，而TreeView最大也是match_parent，允许chilidView超出界面而已。移动后父view整体移动，所以效果上是超出屏幕的部分没有焦点事件。

有问题的解决方法：在FrameLayout外在套一层NoScrollView（无滑动效果），利用ScrollView的界面可以无限大，父view可以完全包裹子view。移动和点击bug可解决。但是，不知道什么原因TreeView刷新不出数据，需要设置setTreeModel后再用handler.sendEmptyMessageDelayed在设置一次setTreeModel，勉强可以用。这个新出现的bug没找到原因~~~

**Comment by owant** [comment]
超出了点击不了是由于父亲没有够大，没有包裹子View导致。

**Comment by handsonpig** [comment]
请问怎么解决？

**Comment by njwl434** [comment]
修改一下MoveAndScaleHandler 里的onTouchEvent 改成自由拖动的，就解决了

**Comment by owant** [comment]
最新版本已经解决了。不用改其他，主要是修改计算
